# Generated by Django 5.2.6 on 2025-09-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(default='0000', max_length=50)),
                ('seats_total', models.IntegerField()),
                ('seats_filled', models.IntegerField(default=0)),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassengerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(default='0000', max_length=50)),
                ('seats_needed', models.IntegerField()),
                ('willing_to_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('flexible_pickup', models.CharField(choices=[('YES', '順路可載'), ('NO', '不順路也OK'), ('MAYBE', '視情況')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('is_matched', models.BooleanField(default=False)),
            ],
        ),
    ]
