# Generated by Django 5.2.6 on 2025-09-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivertrip',
            name='seats_left',
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='seats_filled',
            field=models.IntegerField(default=0),
        ),
    ]
