# Generated by Django 5.2.6 on 2025-09-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertrip',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
