# Generated by Django 5.2.6 on 2025-09-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find', '0002_drivertrip_return_date_passengerrequest_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertrip',
            name='gender',
            field=models.CharField(choices=[('M', '男生'), ('F', '女生'), ('X', '不方便透漏')], default='X', max_length=10),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='gender',
            field=models.CharField(choices=[('M', '男生'), ('F', '女生'), ('X', '不方便透漏')], default='X', max_length=10),
        ),
    ]
