# Generated by Django 5.2.6 on 2025-09-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find', '0002_remove_drivertrip_seats_left_drivertrip_seats_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertrip',
            name='password',
            field=models.CharField(default='0000', max_length=50),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='password',
            field=models.CharField(default='0000', max_length=50),
        ),
    ]
