# Generated by Django 5.2.6 on 2025-09-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find', '0003_drivertrip_gender_passengerrequest_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerrequest',
            name='flexible_pickup',
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='flexible_pickup',
            field=models.CharField(choices=[('YES', '順路可載'), ('NO', '不順路也OK'), ('MAYBE', '視情況')], default='YES', max_length=20),
        ),
    ]
