# Generated by Django 5.2.6 on 2025-09-30 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find', '0004_remove_passengerrequest_flexible_pickup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerrequest',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='Find.drivertrip'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='together_return',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
