# Generated by Django 5.2.6 on 2025-09-30 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find', '0005_passengerrequest_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerrequest',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passengers', to='Find.drivertrip'),
        ),
    ]
