# Generated by Django 5.2.6 on 2025-10-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find', '0006_alter_passengerrequest_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertrip',
            name='fare_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='酌收費用'),
        ),
    ]
