# Generated by Django 5.2.6 on 2025-10-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find', '0007_drivertrip_fare_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertrip',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
