# Generated by Django 5.2.6 on 2025-10-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find', '0008_alter_drivertrip_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertrip',
            name='hide_contact',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='drivertrip',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
