# Generated by Django 5.2.6 on 2025-10-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find', '0009_drivertrip_hide_contact_alter_drivertrip_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerrequest',
            name='driver_memo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='hide_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='drivertrip',
            name='hide_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passengerrequest',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
