# Generated by Django 5.2.6 on 2025-10-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find', '0010_passengerrequest_driver_memo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerrequest',
            name='driver_memo',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
