# Generated by Django 5.2.6 on 2025-10-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find', '0011_alter_passengerrequest_driver_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerrequest',
            name='hide_contact',
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='auto_email_contact',
            field=models.BooleanField(default=False, help_text='（僅在隱藏個資為 True 時生效）自動將你的聯絡方式以 Email 通知已報名的乘客'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='auto_email_contact',
            field=models.BooleanField(default=False, help_text='（僅在隱藏個資為 True 時生效）自動將你的聯絡方式以 Email 通知司機'),
        ),
    ]
