# Generated by Django 5.2.6 on 2025-10-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find', '0012_remove_passengerrequest_hide_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerrequest',
            name='hide_contact',
            field=models.BooleanField(default=False),
        ),
    ]
